### ISSUE TITLE
FS#298 - Build failure in mkmerakifw.c

### ISSUE THREAD

**Issue by aparcar** [aparcar/openwrt#202]
*bjonglez:*

The latest version (r2292) does not build for ar71xx:

<code>
gcc -O2 -I/home/bjonglez/lede-bmon/staging_dir/host/include -I/home/bjonglez/lede-bmon/staging_dir/host/usr/include  -include endian.h -L/home/bjonglez/lede-bmon/staging_dir/host/lib -L/home/bjonglez/lede-bmon/staging_dir/host/usr/lib  -o /home/bjonglez/lede-bmon/build_dir/host/firmware-utils/bin/edimax_fw_header src/edimax_fw_header.c  -Wall
gcc -O2 -I/home/bjonglez/lede-bmon/staging_dir/host/include -I/home/bjonglez/lede-bmon/staging_dir/host/usr/include  -include endian.h -L/home/bjonglez/lede-bmon/staging_dir/host/lib -L/home/bjonglez/lede-bmon/staging_dir/host/usr/lib  -o /home/bjonglez/lede-bmon/build_dir/host/firmware-utils/bin/mkmerakifw src/mkmerakifw.c src/sha1.c  -Wall
src/mkmerakifw.c:75: error: unknown field 'statichash' specified in initializer
src/mkmerakifw.c:75: warning: missing braces around initializer
src/mkmerakifw.c:75: warning: (near initialization for 'boards[0].<anonymous>.statichash')
src/mkmerakifw.c:85: error: unknown field 'statichash' specified in initializer
src/mkmerakifw.c:103: error: unknown field 'mx60' specified in initializer
src/mkmerakifw.c:104: error: unknown field 'kernel_offset' specified in initializer
src/mkmerakifw.c:104: warning: large integer implicitly truncated to unsigned type
src/mkmerakifw.c:105: error: unknown field 'ramdisk_offset' specified in initializer
src/mkmerakifw.c:105: warning: excess elements in union initializer
src/mkmerakifw.c:105: warning: (near initialization for 'boards[2].<anonymous>')
src/mkmerakifw.c:106: error: unknown field 'fdt_offset' specified in initializer
src/mkmerakifw.c:106: warning: excess elements in union initializer
src/mkmerakifw.c:106: warning: (near initialization for 'boards[2].<anonymous>')
src/mkmerakifw.c:107: error: unknown field 'unknown_offset' specified in initializer
src/mkmerakifw.c:107: warning: excess elements in union initializer
src/mkmerakifw.c:107: warning: (near initialization for 'boards[2].<anonymous>')
make[3]: *** [/home/bjonglez/lede-bmon/build_dir/host/firmware-utils/.built] Error 1
make[3]: Leaving directory `/home/bjonglez/lede-bmon/tools/firmware-utils'
make[2]: *** [tools/firmware-utils/compile] Error 2
</code>

This is likely introduced by a72e1692b8b35d61587d75cf1800eef934203cd2 ("firmware-utils: Add support for the Cisco Meraki MX60/MX60W").  Looking at the patch, it indeed seems wrong, as statichash has been moved in a new union but the initializers have not been updated.

<code>$ ./scripts/getver.sh 
r2292
$ ./scripts/diffconfig.sh
CONFIG_TARGET_ar71xx=y      
CONFIG_TARGET_ar71xx_generic=y
CONFIG_TARGET_ar71xx_generic_Default=y
CONFIG_DEVEL=y
CONFIG_DISPLAY_SUPPORT=y
# CONFIG_DRIVER_11N_SUPPORT is not set
# CONFIG_DRIVER_11W_SUPPORT is not set
# CONFIG_PACKAGE_dnsmasq is not set
# CONFIG_PACKAGE_firewall is not set
# CONFIG_PACKAGE_hostapd-common is not set
# CONFIG_PACKAGE_ip6tables is not set
# CONFIG_PACKAGE_iptables is not set
# CONFIG_PACKAGE_iw is not set
# CONFIG_PACKAGE_iwinfo is not set
# CONFIG_PACKAGE_kmod-ath is not set
# CONFIG_PACKAGE_kmod-ath9k is not set
# CONFIG_PACKAGE_kmod-cfg80211 is not set
# CONFIG_PACKAGE_kmod-gpio-button-hotplug is not set
# CONFIG_PACKAGE_kmod-ip6tables is not set
# CONFIG_PACKAGE_kmod-ipt-conntrack is not set
CONFIG_PACKAGE_kmod-ipt-core=m
CONFIG_PACKAGE_kmod-ipt-hashlimit=m
# CONFIG_PACKAGE_kmod-ipt-nat is not set
# CONFIG_PACKAGE_kmod-lib-crc-ccitt is not set
# CONFIG_PACKAGE_kmod-mac80211 is not set
# CONFIG_PACKAGE_kmod-nf-conntrack is not set
# CONFIG_PACKAGE_kmod-nf-conntrack6 is not set
CONFIG_PACKAGE_kmod-nf-ipt=m
# CONFIG_PACKAGE_kmod-nf-ipt6 is not set
# CONFIG_PACKAGE_kmod-nf-nat is not set
# CONFIG_PACKAGE_kmod-ppp is not set
CONFIG_PACKAGE_kmod-udptunnel4=m
CONFIG_PACKAGE_kmod-udptunnel6=m
CONFIG_PACKAGE_kmod-usb3=y
CONFIG_PACKAGE_kmod-wireguard=m
# CONFIG_PACKAGE_libip4tc is not set
# CONFIG_PACKAGE_libip6tc is not set
# CONFIG_PACKAGE_libiwinfo is not set
CONFIG_PACKAGE_libmnl=m
# CONFIG_PACKAGE_libxtables is not set
# CONFIG_PACKAGE_odhcp6c is not set
# CONFIG_PACKAGE_odhcpd is not set
# CONFIG_PACKAGE_ppp is not set
CONFIG_PACKAGE_resolveip=m
# CONFIG_PACKAGE_swconfig is not set
# CONFIG_PACKAGE_uboot-envtools is not set
CONFIG_PACKAGE_wireguard=m
CONFIG_PACKAGE_wireguard-tools=m
# CONFIG_PACKAGE_wpad-mini is not set
CONFIG_TARGET_INITRAMFS_COMPRESSION_NONE=y
CONFIG_TARGET_ROOTFS_INITRAMFS=y
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set</code>
